// <auto-generated by="the Blazor I18n Text compiler" />
namespace n08I18nText.I18nText
{
    public partial class MyText : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextTableHash
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextTableHash.Hash => "564i9lsind";

        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"BarCode"</summary>
        public string BarCode;

        /// <summary>"Edit"</summary>
        public string Edit;

        /// <summary>"Hello,World!"</summary>
        public string HelloWorld;

        /// <summary>"ProductName"</summary>
        public string ProductName;

        /// <summary>"Remark"</summary>
        public string Remark;

        /// <summary>"Save"</summary>
        public string Save;

        /// <summary>"How is Blazor working for you?"</summary>
        public string Tip1;

        /// <summary>"Index"</summary>
        public string Title;

        /// <summary>"Price"</summary>
        public string UnitPrice;

        /// <summary>"View"</summary>
        public string View;
    }
}
